"""MT5 automation tools — compile, test, read results.

Used by Claude Code /mt5 skill. Can also be run standalone:
    python mt5_tools.py compile [GannScalper|GannScalperV92]
    python mt5_tools.py test [options...]
    python mt5_tools.py results
"""

import subprocess
import sys
import os
import glob
import re
import time
from pathlib import Path

# === FIXED PATHS ===
TERMINAL = r"C:\Program Files\RoboForex MT5 Terminal\terminal64.exe"
METAEDITOR = r"C:\Program Files\RoboForex MT5 Terminal\MetaEditor64.exe"
MQL5_DATA = r"C:\Users\Windows 11\AppData\Roaming\MetaQuotes\Terminal\5FFA568149E88FCD5B44D926DCFEAA79\MQL5"
TESTER_DIR = r"C:\Users\Windows 11\AppData\Roaming\MetaQuotes\Terminal\5FFA568149E88FCD5B44D926DCFEAA79\Tester"
TESTER_LOGS = os.path.join(TESTER_DIR, "logs")
PROJECT = r"C:\Users\Windows 11\Desktop\FXSoqqaBot"
EA_DIR = os.path.join(MQL5_DATA, "Experts")
REPORTS_DIR = r"C:\Program Files\RoboForex MT5 Terminal\reports"


def compile_ea(ea_name="GannScalper"):
    """Compile an MQL5 EA. Returns (success: bool, log_text: str)."""
    mq5_file = f"{ea_name}.mq5"
    src = os.path.join(PROJECT, "mql5", mq5_file)
    dst = os.path.join(EA_DIR, mq5_file)
    log_path = os.path.join(PROJECT, "compile.log")

    # Copy source to EA directory
    if not os.path.exists(src):
        return False, f"Source file not found: {src}"

    with open(src, "rb") as f:
        data = f.read()
    with open(dst, "wb") as f:
        f.write(data)
    print(f"Copied {mq5_file} to {EA_DIR}")

    # Remove old log
    if os.path.exists(log_path):
        os.remove(log_path)

    # Compile using PowerShell Start-Process -Wait
    ps_cmd = (
        f'Start-Process -FilePath "{METAEDITOR}" '
        f'-ArgumentList \'/compile:"{dst}" /log:"{log_path}" /inc:"{MQL5_DATA}"\' '
        f'-Wait -NoNewWindow'
    )
    result = subprocess.run(
        ["powershell.exe", "-Command", ps_cmd],
        capture_output=True, text=True, timeout=120
    )

    # Read log
    if os.path.exists(log_path):
        with open(log_path, "rb") as f:
            raw = f.read()
        # Log is UTF-16
        try:
            log_text = raw.decode("utf-16")
        except:
            log_text = raw.decode("utf-8", errors="replace")

        # Check for errors
        match = re.search(r"Result:\s*(\d+)\s*error", log_text)
        errors = int(match.group(1)) if match else -1
        success = errors == 0

        # Filter to just important lines
        important = []
        for line in log_text.splitlines():
            line = line.strip()
            if not line:
                continue
            if "generating code" in line and "%" in line:
                continue  # Skip progress lines
            important.append(line)

        return success, "\n".join(important)
    else:
        return False, "Compilation log not found — MetaEditor may not have run"


def generate_ini(ea_name="GannScalper", **kwargs):
    """Generate a Strategy Tester .ini file. Returns the file path."""
    config = {
        "symbol": "XAUUSD",
        "period": "M5",
        "model": 4,
        "optimization": 0,
        "opt_criterion": 0,
        "from_date": "2020.01.01",
        "to_date": "2026.03.28",
        "forward_mode": 0,
        "forward_date": "",
        "deposit": 20,
        "leverage": 500,
        "visual": 0,
        "shutdown": 1,
    }
    config.update(kwargs)

    # Build report name
    report_name = f"{ea_name}_{config['from_date']}_{config['to_date']}".replace(".", "")
    report_path = f"reports\\{report_name}"

    # Build tester inputs section
    tester_inputs = config.get("tester_inputs", "")

    ini_content = f"""; Auto-generated by mt5_tools.py
[Tester]
Expert={ea_name}.ex5
Symbol={config['symbol']}
Period={config['period']}
Optimization={config['optimization']}
Model={config['model']}
FromDate={config['from_date']}
ToDate={config['to_date']}
ForwardMode={config['forward_mode']}
Deposit={config['deposit']}
Currency=USD
ProfitInPips=0
Leverage={config['leverage']}
ExecutionMode=0
OptimizationCriterion={config['opt_criterion']}
Visual={config['visual']}
Report={report_path}
ReplaceReport=1
ShutdownTerminal={config['shutdown']}
UseLocal=1
UseRemote=0
UseCloud=0
"""

    if tester_inputs:
        ini_content += f"\n[TesterInputs]\n{tester_inputs}\n"

    ini_path = os.path.join(PROJECT, "mt5_test.ini")
    with open(ini_path, "w", encoding="utf-8") as f:
        f.write(ini_content)

    print(f"Generated: {ini_path}")
    print(f"Report will be at: {report_path}")
    return ini_path


def run_test(ini_path=None, wait=True):
    """Launch MT5 Strategy Tester. Returns immediately if wait=False."""
    if ini_path is None:
        ini_path = os.path.join(PROJECT, "mt5_test.ini")

    if not os.path.exists(ini_path):
        print(f"Config not found: {ini_path}")
        return False

    print(f"Launching MT5 Strategy Tester...")
    print(f"Config: {ini_path}")

    if wait:
        ps_cmd = (
            f'Start-Process -FilePath "{TERMINAL}" '
            f'-ArgumentList \'/config:"{ini_path}"\' '
            f'-Wait'
        )
        result = subprocess.run(
            ["powershell.exe", "-Command", ps_cmd],
            capture_output=True, text=True, timeout=600
        )
        print("MT5 Strategy Tester finished.")
        return True
    else:
        subprocess.Popen(
            [TERMINAL, f"/config:{ini_path}"],
            creationflags=subprocess.CREATE_NEW_CONSOLE
        )
        print("MT5 launched in background. Use 'python mt5_tools.py results' to check.")
        return True


def read_results():
    """Read the most recent Strategy Tester results."""
    results = {}

    # 1. Find most recent tester log
    if os.path.exists(TESTER_LOGS):
        logs = sorted(glob.glob(os.path.join(TESTER_LOGS, "*.log")),
                       key=os.path.getmtime, reverse=True)
        if logs:
            log_file = logs[0]
            print(f"\n=== Tester Log: {os.path.basename(log_file)} ===")
            try:
                with open(log_file, "rb") as f:
                    raw = f.read()
                try:
                    text = raw.decode("utf-16")
                except:
                    text = raw.decode("utf-8", errors="replace")

                # Print last 100 lines (most relevant)
                lines = text.splitlines()
                for line in lines[-100:]:
                    print(line)
                results["tester_log"] = text
            except Exception as e:
                print(f"Error reading log: {e}")

    # 2. Find most recent report
    if os.path.exists(REPORTS_DIR):
        reports = sorted(glob.glob(os.path.join(REPORTS_DIR, "*.htm")),
                         key=os.path.getmtime, reverse=True)
        if reports:
            report_file = reports[0]
            print(f"\n=== Report: {os.path.basename(report_file)} ===")
            try:
                with open(report_file, "r", encoding="utf-8", errors="replace") as f:
                    html = f.read()

                # Extract key metrics from HTML
                metrics = extract_metrics_from_html(html)
                for k, v in metrics.items():
                    print(f"  {k}: {v}")
                results["report"] = metrics
                results["report_path"] = report_file
            except Exception as e:
                print(f"Error reading report: {e}")
        else:
            print(f"\nNo HTML reports found in {REPORTS_DIR}")
    else:
        print(f"\nReports directory not found: {REPORTS_DIR}")

    return results


def extract_metrics_from_html(html):
    """Extract key trading metrics from MT5 HTML report."""
    metrics = {}

    patterns = {
        "Total Trades": r'Total Trades.*?<td[^>]*>(\d+)',
        "Profit Trades": r'Profit Trades.*?<td[^>]*>([\d.]+%?)',
        "Loss Trades": r'Loss Trades.*?<td[^>]*>([\d.]+%?)',
        "Total Net Profit": r'Total Net Profit.*?<td[^>]*>([-\d\s.]+)',
        "Gross Profit": r'Gross Profit.*?<td[^>]*>([-\d\s.]+)',
        "Gross Loss": r'Gross Loss.*?<td[^>]*>([-\d\s.]+)',
        "Profit Factor": r'Profit Factor.*?<td[^>]*>([\d.]+)',
        "Expected Payoff": r'Expected Payoff.*?<td[^>]*>([-\d.]+)',
        "Sharpe Ratio": r'Sharpe Ratio.*?<td[^>]*>([-\d.]+)',
        "Balance Drawdown Maximal": r'Balance Drawdown Maximal.*?<td[^>]*>([-\d\s.%]+)',
        "Equity Drawdown Maximal": r'Equity Drawdown Maximal.*?<td[^>]*>([-\d\s.%]+)',
        "Recovery Factor": r'Recovery Factor.*?<td[^>]*>([-\d.]+)',
    }

    for name, pattern in patterns.items():
        match = re.search(pattern, html, re.DOTALL | re.IGNORECASE)
        if match:
            metrics[name] = match.group(1).strip()

    return metrics


def open_terminal():
    """Just open MT5 terminal."""
    subprocess.Popen(
        [TERMINAL],
        creationflags=subprocess.CREATE_NEW_CONSOLE
    )
    print("MT5 Terminal launched.")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python mt5_tools.py [compile|test|results|open] [options]")
        sys.exit(1)

    action = sys.argv[1].lower()

    if action == "compile":
        ea = sys.argv[2] if len(sys.argv) > 2 else "GannScalper"
        success, log = compile_ea(ea)
        print(log)
        sys.exit(0 if success else 1)

    elif action == "test":
        # Parse key=value args
        kwargs = {}
        tester_inputs_lines = []
        ea_name = "GannScalper"
        for arg in sys.argv[2:]:
            if "=" in arg:
                key, val = arg.split("=", 1)
                if key.startswith("Inp"):
                    # EA input parameter
                    tester_inputs_lines.append(f"{key}={val}")
                elif key == "ea":
                    ea_name = val
                else:
                    kwargs[key] = val
            elif arg.lower() in ("v92", "v9.2"):
                ea_name = "GannScalperV92"
            elif arg.lower() == "visual":
                kwargs["visual"] = 1
            elif re.match(r"\d{4}\.\d{2}\.\d{2}", arg):
                if "from_date" not in kwargs:
                    kwargs["from_date"] = arg
                else:
                    kwargs["to_date"] = arg

        if tester_inputs_lines:
            kwargs["tester_inputs"] = "\n".join(tester_inputs_lines)

        ini_path = generate_ini(ea_name, **kwargs)
        run_test(ini_path)

    elif action == "results":
        read_results()

    elif action == "open":
        open_terminal()

    else:
        print(f"Unknown action: {action}")
        sys.exit(1)
